name: quiet
description: 多源音乐播放器

version: 0.10.2
publish_to: none

environment:
  sdk: '>=2.14.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.3
  json_annotation: ^4.4.0
  dio: ^4.0.4
  dio_cookie_manager: 2.0.0
  path_provider: ^2.0.2
  shared_preferences: ^2.0.6
  # url_launcher 最新的 6.1.11 action总是android编译不通过，但是本地又可以
  #  url_launcher: 6.0.20
  url_launcher_platform_interface: ^2.1.0
  url_launcher_windows: ^3.0.6
  url_launcher_linux: ^3.0.5
  intl: ^0.18.0
  sembast: ^3.1.0+2
  scoped_model: ^2.0.0-nullsafety.0
  loader:
    git:
      url: https://github.com/boyan01/loader.git
      ref: e1ef2d9957bc8615c7f19f989d4fcfc142e20e93
  encrypt: ^5.0.0
  scrollable_positioned_list: ^0.3.8
  flutter_hooks: ^0.18.0
  equatable: ^2.0.3
  netease_api:
    path: netease_api/
  kugou_api:
    path: kugou_api/
  kuwo_api:
    path: kuwo_api/
  migu_api:
    path: migu_api/
  path: ^1.8.0
  async: ^2.8.0
  riverpod: ^1.0.3
  flutter_riverpod: ^1.0.3
  hooks_riverpod: ^1.0.3
  # 因为 flutter_localizations 依赖锁死 了 collection 版本
  collection: 1.17.1
  window_manager: ^0.3.4
  lpinyin: ^2.0.3
  stream_transform: ^2.0.0
  windows_taskbar: ^1.1.0+1
  filesize: ^2.0.1
  desktop_drop: ^0.4.0
  dotted_border: ^2.0.0+2
  permission_handler: ^10.2.0
  connectivity_plus: 4.0.1
  list_tile_more_customizable: ^3.0.0
  package_info_plus: 4.0.2
  oktoast: ^3.1.5
  file_picker: 5.3.3
  tray_manager: ^0.2.0
  archive: ^3.3.5
  audioplayers: 4.1.0
  flutter_cache_manager: ^3.1.0
dev_dependencies:
  #  flutter_test:
  #    sdk: flutter
  build_runner: ^2.0.6
  json_serializable: ^6.1.5
  flutter_lints: ^1.0.4

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
flutter_intl:
  enabled: true
